/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockSafeProxyFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createProxy" | "createProxyWithNonce" | "singleton"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProxyCreation"): EventFragment;

  encodeFunctionData(
    functionFragment: "createProxy",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProxyWithNonce",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "singleton", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProxyWithNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "singleton", data: BytesLike): Result;
}

export namespace ProxyCreationEvent {
  export type InputTuple = [proxy: AddressLike, singleton: AddressLike];
  export type OutputTuple = [proxy: string, singleton: string];
  export interface OutputObject {
    proxy: string;
    singleton: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockSafeProxyFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MockSafeProxyFactory;
  waitForDeployment(): Promise<this>;

  interface: MockSafeProxyFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProxy: TypedContractMethod<
    [_singleton: AddressLike, initializer: BytesLike],
    [string],
    "nonpayable"
  >;

  createProxyWithNonce: TypedContractMethod<
    [_singleton: AddressLike, initializer: BytesLike, saltNonce: BigNumberish],
    [string],
    "nonpayable"
  >;

  singleton: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProxy"
  ): TypedContractMethod<
    [_singleton: AddressLike, initializer: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProxyWithNonce"
  ): TypedContractMethod<
    [_singleton: AddressLike, initializer: BytesLike, saltNonce: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "singleton"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProxyCreation"
  ): TypedContractEvent<
    ProxyCreationEvent.InputTuple,
    ProxyCreationEvent.OutputTuple,
    ProxyCreationEvent.OutputObject
  >;

  filters: {
    "ProxyCreation(address,address)": TypedContractEvent<
      ProxyCreationEvent.InputTuple,
      ProxyCreationEvent.OutputTuple,
      ProxyCreationEvent.OutputObject
    >;
    ProxyCreation: TypedContractEvent<
      ProxyCreationEvent.InputTuple,
      ProxyCreationEvent.OutputTuple,
      ProxyCreationEvent.OutputObject
    >;
  };
}
